services:
  devicecapture:
    build:
      context: ./devicecapture
      dockerfile: docker/Dockerfile
    container_name: devicecapture
    networks:
      - openblink
    volumes:
      - ./devicecapture/static/videos:/videos
    depends_on:
      - postgres
    env_file: .env
    restart: unless-stopped
  deviceserver:
    build:
      context: ./devicecapture
      dockerfile: docker/deviceserver.Dockerfile
    container_name: deviceserver
    networks:
      - openblink
    ports:
      - "4000:4000"
    volumes:
      - ./devicecapture/static/videos:/videos
      - ./devicecapture/static:/usr/src/app/static
    depends_on:
      - postgres
    env_file: .env
    restart: unless-stopped
  test:
    build:
      context: ./devicecapture
      dockerfile: docker/test.Dockerfile
    networks:
      - openblink
    volumes:
      - ./devicecapture:/usr/src/app
    depends_on:
      - postgres
    env_file: .env.example
  postgres:
    image: postgres:16-alpine3.22
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - openblink
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./devicecapture/internal/postgres/sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./devicecapture/docker/init-databases.sql:/docker-entrypoint-initdb.d/02-init-databases.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  openblink:
    driver: bridge
volumes:
  postgres_data:
