services:
  blink_detection_service:
    container_name: blink_detection_service
    build: ./detection_service
    depends_on:
      - mosquitto
    networks:
      - mosquitto
    volumes:
      - ./videos:/videos
    environment:
      - MQTT_HOST='mosquitto'
    restart: unless-stopped
  devicecapture:
    build: ./devicecapture
    container_name: devicecapture
    depends_on:
      - mosquitto
    networks:
      - mosquitto
    volumes:
      - ./videos:/videos
    environment:
      - MQTT_HOST='mosquitto:1833'
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    networks:
      - mosquitto
    ports:
      - "1883:1883" # Standard MQTT port
      - "9001:9001" # Websocket port for MQTT
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    restart: unless-stopped

networks:
  mosquitto:
    driver: bridge