services:
  device-service:
    build: ./device_service
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: openblink
      POSTGRES_USER: openblink
      POSTGRES_PASSWORD: openblink
    ports:
      - "5432:5432" # Optional: for host access
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: