services:
  blink_detection_service:
    container_name: blink_detection_service
    build: ./detection_service
    depends_on:
      - mosquitto
    networks:
      - openblink
    volumes:
      - ./videos:/videos
    environment:
      - MQTT_HOST='mosquitto'
    restart: unless-stopped
  devicecapture:
    build: ./devicecapture
    container_name: devicecapture
    networks:
      - openblink
    volumes:
      - ./videos:/videos
    depends_on:
      - mosquitto
    environment:
      - MQTT_HOST='192.168.0.33'
    restart: unless-stopped
  mock_device:
    build:
      context: ./devicecapture
      dockerfile: mockdevice.Dockerfile
    container_name: mock_device
    networks:
      - openblink
    ports:
      - "8080:8080"
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    networks:
      - openblink
    ports:
      - "1883:1883" # Standard MQTT port
      - "9001:9001" # Websocket port for MQTT
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    restart: unless-stopped

networks:
  openblink:
    driver: bridge