services:
  devicecapture:
    build: docker/Dockerfile
    volumes:
      - ./videos:/videos
    environment:
      - MQTT_HOST='host.docker.internal:1833'
      - DB_URL='postgres://postgres:postgres@postgres:5432/openblink'
    depends_on:
      postgres:
        condition: service_healthy
  mockdevice:
    build: docker/mockdevice.Dockerfile
    ports:
      - "8080:8080"
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    networks:
      - openblink
    ports:
      - "1883:1883" # Standard MQTT port
      - "9001:9001" # Websocket port for MQTT
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    restart: unless-stopped
  postgres:
    image: postgres:16-alpine3.22
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/postgres/sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./docker/init-databases.sql:/docker-entrypoint-initdb.d/02-init-databases.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  openblink:
    driver: bridge