// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api.sql

package db

import (
	"context"
	"time"
)

const getDetectionImagesByLabel = `-- name: GetDetectionImagesByLabel :many
SELECT detections.id,
       detections.created_at,
       detections.label,
       detections.confidence,
       detections.bbox,
       detections.device_id,
       device_images.image_path
FROM detections
         JOIN device_images ON device_images.id = detections.id
WHERE label ILIKE ANY ($1::text[])
  AND (
    CASE
        WHEN $2::bigint = 0
            THEN detections.device_id IS NOT NULL
        ELSE detections.device_id = $2
        END
    )
  AND (
    CASE
        WHEN $3::timestamp with time zone IS NOT NULL
            THEN detections.created_at >= $3
        ELSE detections.created_at >= NOW() - INTERVAL '7 days'
        END
    )
ORDER BY detections.created_at DESC
`

type GetDetectionImagesByLabelParams struct {
	Label     []string  `db:"label" json:"label"`
	DeviceID  int64     `db:"device_id" json:"device_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type GetDetectionImagesByLabelRow struct {
	ID         int64       `db:"id" json:"id"`
	CreatedAt  time.Time   `db:"created_at" json:"created_at"`
	Label      string      `db:"label" json:"label"`
	Confidence float64     `db:"confidence" json:"confidence"`
	Bbox       [][]float64 `db:"bbox" json:"bbox"`
	DeviceID   int64       `db:"device_id" json:"device_id"`
	ImagePath  string      `db:"image_path" json:"image_path"`
}

func (q *Queries) GetDetectionImagesByLabel(ctx context.Context, arg GetDetectionImagesByLabelParams) ([]GetDetectionImagesByLabelRow, error) {
	rows, err := q.db.Query(ctx, getDetectionImagesByLabel, arg.Label, arg.DeviceID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDetectionImagesByLabelRow{}
	for rows.Next() {
		var i GetDetectionImagesByLabelRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Label,
			&i.Confidence,
			&i.Bbox,
			&i.DeviceID,
			&i.ImagePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentLabels = `-- name: GetRecentLabels :many
SELECT DISTINCT(label)
FROM detections
WHERE created_at > NOW() - INTERVAL '7 days'
`

// ----------------------------
// Detection API
// -------------------------------
func (q *Queries) GetRecentLabels(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getRecentLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
