// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: archiver.sql

package db

import (
	"context"
)

const getArchiveTargets = `-- name: GetArchiveTargets :many
SELECT id, device_id, created_at, image_path
FROM device_images
WHERE created_at >= (NOW() - INTERVAL '7 days')
ORDER BY created_at
LIMIT 500
`

// ----------------------------
// Image/Asset archive queries
// -------------------------------
func (q *Queries) GetArchiveTargets(ctx context.Context) ([]DeviceImage, error) {
	rows, err := q.db.Query(ctx, getArchiveTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceImage{}
	for rows.Next() {
		var i DeviceImage
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.CreatedAt,
			&i.ImagePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldestTargets = `-- name: PurgeOldestTargets :exec
DELETE
FROM device_images
WHERE id IN (SELECT id
             FROM device_images
             WHERE created_at >= (NOW() - INTERVAL '7 days')
             ORDER BY created_at
             LIMIT 500)
`

func (q *Queries) PurgeOldestTargets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeOldestTargets)
	return err
}

const setArchived = `-- name: SetArchived :exec
UPDATE device_images
SET image_path = $1
WHERE id = $2
`

type SetArchivedParams struct {
	ImagePath string `db:"image_path" json:"image_path"`
	ID        int64  `db:"id" json:"id"`
}

func (q *Queries) SetArchived(ctx context.Context, arg SetArchivedParams) error {
	_, err := q.db.Exec(ctx, setArchived, arg.ImagePath, arg.ID)
	return err
}
