// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateDetections implements pgx.CopyFromSource.
type iteratorForCreateDetections struct {
	rows                 []CreateDetectionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateDetections) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateDetections) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].DeviceID,
		r.rows[0].Label,
		r.rows[0].Confidence,
		r.rows[0].ImageID,
	}, nil
}

func (r iteratorForCreateDetections) Err() error {
	return nil
}

func (q *Queries) CreateDetections(ctx context.Context, arg []CreateDetectionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"detections"}, []string{"device_id", "label", "confidence", "image_id"}, &iteratorForCreateDetections{rows: arg})
}
