// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"time"
)

const endEvent = `-- name: EndEvent :one
UPDATE detection_events
SET state    = 3,
    ended_at = NOW()
WHERE id = $1
RETURNING id, device_id, created_at, ended_at, labels, state
`

func (q *Queries) EndEvent(ctx context.Context, id int64) (DetectionEvent, error) {
	row := q.db.QueryRow(ctx, endEvent, id)
	var i DetectionEvent
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.EndedAt,
		&i.Labels,
		&i.State,
	)
	return i, err
}

const endStaleDetectionEvents = `-- name: EndStaleDetectionEvents :exec
UPDATE detection_events
SET ended_at = NOW(),
    state    = 3
WHERE ended_at = '0001-01-01 00:00:00.000000 +00:00'
`

func (q *Queries) EndStaleDetectionEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, endStaleDetectionEvents)
	return err
}

const getEventDetails = `-- name: GetEventDetails :many
SELECT detection_events.id, detection_events.device_id, detection_events.created_at, detection_events.ended_at, detection_events.labels, detection_events.state,
       device_images.id      AS image_id,
       device_images.annotated_path,
       device_images.image_path,
       detections.id         AS detection_id,
       detections.label,
       detections.confidence,
       detections.created_at AS detected_at,
       detections.bbox,
       detections.image_id   AS detected_image_id
FROM detection_events
         JOIN device_images ON device_images.device_id = detection_events.device_id
         JOIN detections ON detections.image_id = device_images.id
WHERE detection_events.id = $1
  AND detections.created_at >= detection_events.created_at
  AND detections.created_at <= detection_events.ended_at
LIMIT 100
`

type GetEventDetailsRow struct {
	ID              int64       `db:"id" json:"id"`
	DeviceID        int64       `db:"device_id" json:"device_id"`
	CreatedAt       time.Time   `db:"created_at" json:"created_at"`
	EndedAt         time.Time   `db:"ended_at" json:"ended_at"`
	Labels          string      `db:"labels" json:"labels"`
	State           int         `db:"state" json:"state"`
	ImageID         int64       `db:"image_id" json:"image_id"`
	AnnotatedPath   *string     `db:"annotated_path" json:"annotated_path"`
	ImagePath       string      `db:"image_path" json:"image_path"`
	DetectionID     int64       `db:"detection_id" json:"detection_id"`
	Label           string      `db:"label" json:"label"`
	Confidence      float64     `db:"confidence" json:"confidence"`
	DetectedAt      time.Time   `db:"detected_at" json:"detected_at"`
	Bbox            [][]float64 `db:"bbox" json:"bbox"`
	DetectedImageID *int64      `db:"detected_image_id" json:"detected_image_id"`
}

func (q *Queries) GetEventDetails(ctx context.Context, id int64) ([]GetEventDetailsRow, error) {
	rows, err := q.db.Query(ctx, getEventDetails, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventDetailsRow{}
	for rows.Next() {
		var i GetEventDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.CreatedAt,
			&i.EndedAt,
			&i.Labels,
			&i.State,
			&i.ImageID,
			&i.AnnotatedPath,
			&i.ImagePath,
			&i.DetectionID,
			&i.Label,
			&i.Confidence,
			&i.DetectedAt,
			&i.Bbox,
			&i.DetectedImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvents = `-- name: GetEvents :many
SELECT id, device_id, created_at, ended_at, labels, state
FROM detection_events
WHERE (
    CASE
        WHEN $1::bigint = 0
            THEN detection_events.device_id IS NOT NULL
        ELSE detection_events.device_id = $1
        END
    )
  AND (
    CASE
        WHEN $2::int = 0
            THEN detection_events.state IS NOT NULL
        ELSE detection_events.state = $2
        END
    )
  AND (
    CASE
        WHEN $3::timestamp = '0001-01-01 00:00:00.000000 +00:00'
            THEN detection_events.created_at IS NOT NULL
        ELSE detection_events.created_at >= $3
        END
    )
  AND (
    CASE
        WHEN $4::timestamp = '0001-01-01 00:00:00.000000 +00:00'
            THEN detection_events.created_at IS NOT NULL
        ELSE detection_events.created_at <= $4
        END
    )
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type GetEventsParams struct {
	DeviceID int64     `db:"device_id" json:"device_id"`
	State    int32     `db:"state" json:"state"`
	Startdt  time.Time `db:"startdt" json:"startdt"`
	Enddt    time.Time `db:"enddt" json:"enddt"`
	Off      int32     `db:"off" json:"off"`
	Lim      int32     `db:"lim" json:"lim"`
}

func (q *Queries) GetEvents(ctx context.Context, arg GetEventsParams) ([]DetectionEvent, error) {
	rows, err := q.db.Query(ctx, getEvents,
		arg.DeviceID,
		arg.State,
		arg.Startdt,
		arg.Enddt,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectionEvent{}
	for rows.Next() {
		var i DetectionEvent
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.CreatedAt,
			&i.EndedAt,
			&i.Labels,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startEvent = `-- name: StartEvent :one
INSERT INTO detection_events(id, device_id, created_at, ended_at, labels, state)
VALUES (DEFAULT, $1, DEFAULT, $2, $3, $4)
RETURNING id, device_id, created_at, ended_at, labels, state
`

type StartEventParams struct {
	DeviceID int64     `db:"device_id" json:"device_id"`
	EndedAt  time.Time `db:"ended_at" json:"ended_at"`
	Labels   string    `db:"labels" json:"labels"`
	State    int       `db:"state" json:"state"`
}

func (q *Queries) StartEvent(ctx context.Context, arg StartEventParams) (DetectionEvent, error) {
	row := q.db.QueryRow(ctx, startEvent,
		arg.DeviceID,
		arg.EndedAt,
		arg.Labels,
		arg.State,
	)
	var i DetectionEvent
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.EndedAt,
		&i.Labels,
		&i.State,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE detection_events
SET labels     =
        CASE
            WHEN $1::bool
                THEN $2::text
            ELSE labels
            END,
    state      =
        CASE
            WHEN $3::bool
                THEN $4::INT
            ELSE state
            END,
    created_at =
        CASE
            WHEN $5::bool
                THEN $6::timestamp
            ELSE created_at
            END,
    ended_at   =
        CASE
            WHEN $7::bool
                THEN $8::timestamp
            ELSE ended_at
            END
WHERE id = $9
RETURNING id, device_id, created_at, ended_at, labels, state
`

type UpdateEventParams struct {
	SetLabels    bool      `db:"set_labels" json:"set_labels"`
	Labels       string    `db:"labels" json:"labels"`
	SetState     bool      `db:"set_state" json:"set_state"`
	State        int32     `db:"state" json:"state"`
	SetCreatedAt bool      `db:"set_created_at" json:"set_created_at"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	SetEndedAt   bool      `db:"set_ended_at" json:"set_ended_at"`
	EndedAt      time.Time `db:"ended_at" json:"ended_at"`
	ID           int64     `db:"id" json:"id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (DetectionEvent, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.SetLabels,
		arg.Labels,
		arg.SetState,
		arg.State,
		arg.SetCreatedAt,
		arg.CreatedAt,
		arg.SetEndedAt,
		arg.EndedAt,
		arg.ID,
	)
	var i DetectionEvent
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.EndedAt,
		&i.Labels,
		&i.State,
	)
	return i, err
}
